use_frameworks!

target 'BLPopController_Example' do
  pod 'BLPopController', :path => '../'

  target 'BLPopController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
